### ISSUE TITLE
Improve dependency management

### ISSUE THREAD

**Issue by xavikortes** [starkraving/slotted-react-component#30]
Hey, I found your repo searching for react slots in google, and I think it's a great idea. Congratulations.

But one thing you should consider is to improve the dependency management.

Now, the package dependencies includes some dependencies for testing, another for create apps, and a dependency for itself.

Maybe you should consider move this dependencies into 'devDependencies' in your package.json.

In case you dont't know how it is, you can reinstall theme with `npm i -D package`

**Comment by starkraving** [comment]
Hi, thanks for the feedback. This repository actually contains both the demo for the hook (which is the main package.json) and the hook itself, which is in src/hook and has its own package.json. When you run `npm install use-componentslots` it pulls down just the hook, not the rest of the Github repository.

Having said that, the hook's own package.json could probably switch to using peer dependencies for React, so I'll update that.

Thanks again for the feedback!
